initStore([
  {
    id: 0,
    title: 'Phantom Core: Reawakening (PC/PS5)',
    description: 'Dive into a futuristic open-world shooter with next-gen visuals and an immersive narrative.',
    price: 69.95,
    discountPrice: 54.95,
    image: 'images/service-1.jpg',
  },
  {
    id: 1,
    title: 'Strikepoint Elite (PC/PS5/Xbox)',
    description: 'Tactical FPS with dynamic multiplayer arenas and a high-stakes campaign mode.',
    price: 79.95,
    discountPrice: 59.95,
    image: 'images/service-2.jpg',
  },
  {
    id: 2,
    title: 'Kingdoms Unbound (Switch)',
    description: 'Explore enchanted realms in this epic fantasy RPG with deep exploration and puzzle mechanics.',
    price: 69.95,
    discountPrice: 62.95,
    image: 'images/service-3.jpg',
  },
  {
    id: 3,
    title: 'Ultimate Kickoff 25 (PC/PS5/Xbox)',
    description: 'Hyper-realistic football simulation with updated mechanics and advanced AI gameplay.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'images/service-4.jpg',
  },
  {
    id: 4,
    title: 'Dark Ascent: Isolation (PC/PS5/Xbox)',
    description: 'Atmospheric survival horror game with gripping storylines and intense stealth elements.',
    price: 39.95,
    discountPrice: 29.95,
    image: 'images/service-5.jpg',
  },
  {
    id: 5,
    title: 'Battleverse: Ultimate Rumble (Switch)',
    description: 'Fast-paced fighting game with a massive roster and thrilling competitive gameplay.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'images/service-6.jpg',
  },
]);