initStore([
  {
    id: 0,
    title: 'Elden Ring (PC/PS5/Xbox)',
    description: 'An expansive action RPG developed by FromSoftware, offering a vast open world filled with challenging enemies, mysterious lore, and deep customization. Journey through the Lands Between and forge your destiny in a dark fantasy epic.',
    price: 69.95,
    discountPrice: 54.95,
    image: 'images/service-1.jpg',
  },
  {
    id: 1,
    title: 'Call of Duty: Modern Warfare II (PC/PS5/Xbox)',
    description: 'Experience the next chapter in the legendary shooter franchise with a cinematic campaign, realistic gunplay, and a massive multiplayer suite packed with maps, modes, and seasonal content.',
    price: 79.95,
    discountPrice: 59.95,
    image: 'images/service-2.jpg',
  },
  {
    id: 2,
    title: 'The Legend of Zelda: Tears of the Kingdom (Switch)',
    description: 'Sequel to the award-winning Breath of the Wild, this open-world adventure lets players explore floating islands, uncover secrets, and manipulate time and space in a beautifully realized fantasy world.',
    price: 69.95,
    discountPrice: 62.95,
    image: 'images/service-3.jpg',
  },
  {
    id: 3,
    title: 'EA Sports FC 24 (PC/PS5/Xbox)',
    description: 'Featuring real player motion and HyperMotionV technology, this next-gen football simulator delivers ultra-realistic gameplay, updated rosters, and hundreds of licensed teams and leagues from around the world.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'images/service-4.jpg',
  },
  {
    id: 4,
    title: 'Resident Evil Village (PC/PS5/Xbox)',
    description: 'Enter a chilling village and face terrifying creatures in this survival horror masterpiece. With a gripping storyline, stunning visuals, and intense gameplay, it continues the saga of Ethan Winters in a new nightmare.',
    price: 39.95,
    discountPrice: 29.95,
    image: 'images/service-5.jpg',
  },
  {
    id: 5,
    title: 'Super Smash Bros. Ultimate (Switch)',
    description: 'Battle it out with a massive roster of iconic characters in this ultimate fighting game experience. Featuring dynamic stages, endless combos, and local or online multiplayer, it’s a celebration of gaming history.',
    price: 59.95,
    discountPrice: 49.95,
    image: 'images/service-6.jpg',
  },
]);